//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessClub.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public System.DateTime VisitDateTime { get; set; }
        public Nullable<int> WorkoutId { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Workouts Workouts { get; set; }
    }
}
